spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    type: single
    single:
      address: 10.1.86.119:6303
      password: XGVKwO3s

  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.86.119:33301/shuangjian?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=GMT%2B8&
    username: xxl_job
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 50
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

  servlet:
    multipart:
      enabled: true
      max-file-size: 400MB
      max-request-size: 400MB

logging:
  config: classpath:logger/logback-test.xml